### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by theofficialvkr** [ABob/y-dl-on-a-server#1]
Hi it is really the best youtube dl interface but I want you to add some features so it become amazing ..
1 -  Show processing or converting gif 
2- when conversion complete automatically redirect to the download page 
Thats it ..

**Comment by ABob** [comment]
Hi therealvk,
thanks for your kind feedback! I'm glad you use and like this little project. Unfortunately, I just have little time to maintain it, that's the reason for my late answer. For your two suggestions:
1 - There already is a little "work in progress" animation for unfinished downloads. Do you mean something different or more elaborated?
2- I think it's not a good idea to automatically redirect to the download page after a download has finished as you could just be in the process of adding a new download job and would be interrupted like this. Instead, there now will be shown a download link that directly refers to the result file when a download was finished. 
I hope this fits for your use case.

**Comment by theofficialvkr** [comment]
Thanks
